### ISSUE TITLE
Latest 1.4.1 tab issue with safari 9 on yosemite

### ISSUE THREAD

**Issue by ssmith-smart421** [inket/cosyTabs#11]
Hi, tried your 1.4.1 just now for the double click to open fix.

I'm on safari 9, but with Yosemite.

It unfortunately made things worse there - basically - double click still does nothing, but in addition, you can now not select the first tab that is open at all. e.g. once used + to open several tabs, trying to select the left most tab is ignored. So going back to 1.4 for now.

**Comment by inket** [comment]
Thank you for reporting it! This is quite difficult because Safari 9 on El Capitan is different from the one in Yosemite.

I suggest Yosemite users stick to 1.4 for now.
