### ISSUE TITLE
(1.4.3) No tab name with one opened tab

### ISSUE THREAD

**Issue by the3ye** [inket/cosyTabs#14]
v1.4.3 running on Safari 10.0 on OSX 10.11.6

![zrzut ekranu 2016-09-23 o 21 52 58](https://cloud.githubusercontent.com/assets/13607809/18799488/1ec0f6a6-81d8-11e6-8ea6-022434456aeb.png)
![zrzut ekranu 2016-09-23 o 21 53 48](https://cloud.githubusercontent.com/assets/13607809/18799509/3b0b43de-81d8-11e6-9e0a-33a6000e3417.png)

**Comment by inket** [comment]
Hi! I haven't tested Safari 10 with El Capitan.

It seems that at every OS/Safari release, the binary for each OS is different. It would need a lot of work to support Safari 10 with El Capitan so this time I'm opting to not support it. It is extra work considering that everyone will be updating to macOS Sierra anyway.

You can still use this plugin once you update your OS.

**Comment by remyvv** [comment]
Hi!
I'm having the same problem on an freshly installed macOS Sierra installation.
Steps to reproduce:

1. Open 2 tabs.
2. Pin 1 of those tabs.

Let me know if you need any extra information, or if i need to submit this in a separate issue.

**Comment by the3ye** [comment]
Just installed Sierra (fresh install) and that problem is still present. Safari 10.0 (12602.1.50.0.10)

**Comment by inket** [comment]
Thank you for reporting it! I will look into it tonight.

**Comment by inket** [comment]
Hi again,

Can you try the [new version](https://github.com/inket/cosyTabs/releases/tag/v1.4.4) to see if the problem persists?

**Comment by the3ye** [comment]
Looks good so far!

**Comment by inket** [comment]
I'm guessing this is resolved. Thank you for reporting the issue!
