### ISSUE TITLE
Double-clicking the tab bar doesn't create a new tab

### ISSUE THREAD

**Issue by inket** [inket/cosyTabs#8]
^

**Comment by the3ye** [comment]
hope we get a fix for that. I miss double-clicking.
Thanks in advance!

**Comment by inket** [comment]
@the3ye @hufufuf How about a single click instead of a double-click?

Because I have that working now (by chance) and it might need work to make it a double-click so I'm thinking if that's even necessary.

**Comment by hufufuf** [comment]
It's great for me. 
Single or double click, i don't really care. It will probably take a couple of days to get used to it but I don't see any reason it would bother me after that. 

Good work and thanks !

**Comment by the3ye** [comment]
Single click is still better than + button or cmd+t :+1:

**Comment by inket** [comment]
Great. Thanks!

**Comment by the3ye** [comment]
Awesome!
Small bugs though:
1. After opening Safari (fresh start) first tab is wide, next one makes it short. When one tab is left open, clicking on bar doesn't make new tab to appear. 
2. New Safari window makes first tab to be short but clicking still doesn't work. Need to have at least two tabs open for clicking to be working.

**Comment by inket** [comment]
> 1\. After opening Safari (fresh start) first tab is wide, next one makes it short. When one tab is left open, clicking on bar doesn't make new tab to appear. 

That seems to be dependant on how fast the plugin loads (i.e. your computer's specs), I'll have another go at fixing it.

> 2\. New Safari window makes first tab to be short but clicking still doesn't work. Need to have at least two tabs open for clicking to be working.

That's true. I didn't notice because I have pinned tabs. Will take a look.
